export const cities: any = [
    {
        id: "ZWL005764",
        label: "Sarita Vihar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008752",
        label: "Faridabad Sector 41-50",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005996",
        label: "New Friends Colony",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005243",
        label: "Sector 26 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009032",
        label: "New Industrial Town",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005428",
        label: "Tilak Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001073",
        label: "Sector 10, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001319",
        label: "Ashok Vihar, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004800",
        label: "Kalkaji",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003118",
        label: "Sector 53",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002091",
        label: "Sector 49",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002662",
        label: "Vasundhara",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001404",
        label: "Rajinder Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008963",
        label: "Safdarjung Enclave",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006538",
        label: "Connaught Place",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003075",
        label: "Sector 66",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003721",
        label: "Sector 57",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006396",
        label: "Moti Bagh, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004535",
        label: "Patel Nagar, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008554",
        label: "Greater Noida",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004533",
        label: "Karkardooma, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002179",
        label: "Tigaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007487",
        label: "Sector 50 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007120",
        label: "Vasant Kunj, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007486",
        label: "Dwarka, Delhi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006287",
        label: "Sector 15",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002146",
        label: "Mayur Vihar Phase III",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008405",
        label: "Crossing Republik",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004455",
        label: "Sector 28",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005087",
        label: "Palam Vihar, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009648",
        label: "Sector 63 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008317",
        label: "Raj Nagar, Ghaziabad",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005878",
        label: "Sector 128",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003241",
        label: "Sector 56, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007224",
        label: "Indirapuram",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009834",
        label: "Malviya Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007284",
        label: "Sector 43, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006738",
        label: "Sector 120 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007329",
        label: "Saket",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001752",
        label: "Sector 18 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007594",
        label: "Naraina",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006116",
        label: "Patparganj",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009925",
        label: "Ghitorni",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009335",
        label: "Faridabad Sector 1-11",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009638",
        label: "Sector 24",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005670",
        label: "Rajouri Garden",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003757",
        label: "Vishnu Garden",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003610",
        label: "Sector 48, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005971",
        label: "Kirti Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003626",
        label: "Faridabad Sector 81-89",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005876",
        label: "GK I",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006295",
        label: "Mohan Estate",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007653",
        label: "Mukherjee Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006697",
        label: "Mehrauli",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003259",
        label: "Burari",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004759",
        label: "Gaur city, Ghaziabad",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004477",
        label: "GK II",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005077",
        label: "Rohini",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008191",
        label: "Rangpuri",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006092",
        label: "Sector 46",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001549",
        label: "Sector 62 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001036",
        label: "Shalimar Bagh",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006996",
        label: "Model Town",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007566",
        label: "Faridabad Sector 16-20",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009852",
        label: "Sector 2 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008648",
        label: "Govindpuram",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009728",
        label: "Gwal Pahari",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006868",
        label: "Nehru Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002067",
        label: "Chittaranjan Park",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008791",
        label: "IMT Manesar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003043",
        label: "Sector 73 Z Kitchen",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004159",
        label: "Sector 51",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005960",
        label: "Ballabhgarh",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009293",
        label: "Nangloi",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001663",
        label: "Uttam Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005762",
        label: "Sector 47",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005345",
        label: "Paharganj",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008225",
        label: "Sector 25",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001933",
        label: "Pitampura",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003591",
        label: "Shahdara",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007061",
        label: "Sector 31",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008476",
        label: "Sector 23",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009008",
        label: "Sector 12 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005323",
        label: "Mayur Vihar Phase II",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001412",
        label: "Faridabad Sector 12-15",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005925",
        label: "DLF PHASE 1 (SECTOR 26)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008716",
        label: "Laxmi Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009339",
        label: "Karol Bagh",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009096",
        label: "Chhatarpur",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006720",
        label: "Paschim Vihar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002908",
        label: "Sector 1, Noida",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001186",
        label: "South Extension I",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004789",
        label: "Sector 18",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008978",
        label: "Kamla Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007903",
        label: "Janakpuri",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008897",
        label: "Vikaspuri",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007431",
        label: "Najafgarh",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001112",
        label: "Mayur Vihar Phase 1",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008649",
        label: "Sez Noida 1",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006384",
        label: "Gulavali, Noida",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007840",
        label: "Sector 14",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002072",
        label: "Sector 76(Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003077",
        label: "Green Park",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005395",
        label: "Munirka",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005729",
        label: "NEHRU PLACE",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL005736",
        label: "Lajpat Nagar",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007212",
        label: "Sector 52 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL004803",
        label: "Sector 100 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003444",
        label: "Sector 50",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008293",
        label: "Dilshad Garden",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007308",
        label: "Sector 29, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008219",
        label: "SUSHANT LOK 1",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL006234",
        label: "SAHIBABAD",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007666",
        label: "Sector 45 (Noida)",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL002490",
        label: "Sector 84",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL007138",
        label: "Sector 7, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL009706",
        label: "Sector 27",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001267",
        label: "Hauz Khas",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003552",
        label: "Jangpura",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL008401",
        label: "Sector 52, Gurgaon",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL001758",
        label: "Vaishali, Ghaziabad",
        cityName: "Delhi NCR",
    },
    {
        id: "ZWL003128",
        label: "Shibpur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL004322",
        label: "Kalyani 1, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL002495",
        label: "Bansdroni",
        cityName: "Kolkata",
    },
    {
        id: "ZWL009257",
        label: "Bow Barracks",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005435",
        label: "Baranagar, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007041",
        label: "Sonarpur, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL002918",
        label: "Ballygunge",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003388",
        label: "Sinthi, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008806",
        label: "Salt Lake 2",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008635",
        label: "Alipore",
        cityName: "Kolkata",
    },
    {
        id: "ZWL002312",
        label: "Baguihati",
        cityName: "Kolkata",
    },
    {
        id: "ZWL001499",
        label: "South Dum Dum",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003315",
        label: "Purba Barisha",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003794",
        label: "Jadavpur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL006574",
        label: "Tollygunge",
        cityName: "Kolkata",
    },
    {
        id: "ZWL004138",
        label: "Shyam Bazar",
        cityName: "Kolkata",
    },
    {
        id: "ZWL009022",
        label: "Behala",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003271",
        label: "Chandannagar, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003951",
        label: "Barrackpore",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003915",
        label: "East Kolkata Township",
        cityName: "Kolkata",
    },
    {
        id: "ZWL006750",
        label: "Bhowanipore",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008828",
        label: "Elgin",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008426",
        label: "Howrah",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007323",
        label: "New Alipore",
        cityName: "Kolkata",
    },
    {
        id: "ZWL006266",
        label: "Barasat",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008393",
        label: "New Town (kolkata)",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007966",
        label: "Uttarpara",
        cityName: "Kolkata",
    },
    {
        id: "ZWL001039",
        label: "Santoshpur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003882",
        label: "Liluah",
        cityName: "Kolkata",
    },
    {
        id: "ZWL004925",
        label: "Rajarhat",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005244",
        label: "Park Street area",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003687",
        label: "Baghajatin Colony",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008120",
        label: "Shrirampur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007514",
        label: "Chhota Jagulia",
        cityName: "Kolkata",
    },
    {
        id: "ZWL003935",
        label: "Dum Dum",
        cityName: "Kolkata",
    },
    {
        id: "ZWL002931",
        label: "Kestopur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL006521",
        label: "Sodepur",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005558",
        label: "Nimta",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005174",
        label: "Shapoorji",
        cityName: "Kolkata",
    },
    {
        id: "ZWL002488",
        label: "Barabazar Market",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007934",
        label: "Salt Lake 1",
        cityName: "Kolkata",
    },
    {
        id: "ZWL001584",
        label: "Tangra",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005429",
        label: "Gariahat",
        cityName: "Kolkata",
    },
    {
        id: "ZWL005121",
        label: "Santragachi",
        cityName: "Kolkata",
    },
    {
        id: "ZWL007830",
        label: "Garia",
        cityName: "Kolkata",
    },
    {
        id: "ZWL008991",
        label: "Chinsurah, Kolkata",
        cityName: "Kolkata",
    },
    {
        id: "ZWL009194",
        label: "Kankurgachi",
        cityName: "Kolkata",
    },
    {
        id: "ZWL004722",
        label: "Kasba",
        cityName: "Kolkata",
    },
    {
        id: "ZWL006536",
        label: "Mira Road East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004934",
        label: "Kandivali West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004821",
        label: "Boisar, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007249",
        label: "Bhiwandi",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001164",
        label: "Panvel",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009537",
        label: "Kopar Khairane (Navi Mumbai)",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007275",
        label: "Vashi",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002556",
        label: "Titwala, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006937",
        label: "Kandivali East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008636",
        label: "Nalasopara",
        cityName: "Mumbai",
    },
    {
        id: "ZWL003995",
        label: "Lower Parel",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006938",
        label: "Goregaon East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008550",
        label: "Santacruz East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004494",
        label: "Ghatkopar East, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL003708",
        label: "Palava",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008711",
        label: "Malad West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL005991",
        label: "Borivali East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002865",
        label: "Kalyan,West,Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004749",
        label: "Santacruz West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001274",
        label: "Badlapur, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007699",
        label: "Ambernath",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001764",
        label: "Marine lines",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002921",
        label: "Mulund West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001410",
        label: "Airoli",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009757",
        label: "Kharghar (Navi Mumbai)",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002059",
        label: "Ulhasnagar (Mumbai)",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001058",
        label: "Ghatkopar West, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006995",
        label: "Bandra West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004692",
        label: "Dadar West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007667",
        label: "Andheri West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009338",
        label: "Vile Parle West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009167",
        label: "Byculla",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006032",
        label: "Vasai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007397",
        label: "Kalyan,East (Mumbai)",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009360",
        label: "Ulwe, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002205",
        label: "Fort",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008975",
        label: "Andheri East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009252",
        label: "Chembur",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002558",
        label: "Palghar, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002742",
        label: "Mumbra, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004971",
        label: "Mulund East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008348",
        label: "Shirdhon, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001344",
        label: "Virar",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007606",
        label: "Tardeo",
        cityName: "Mumbai",
    },
    {
        id: "ZWL005697",
        label: "Bandra East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL005442",
        label: "Thane West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL004189",
        label: "Kurla West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL005000",
        label: "Goregaon West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002056",
        label: "Hiranandani Estate",
        cityName: "Mumbai",
    },
    {
        id: "ZWL009826",
        label: "Dombivli",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007889",
        label: "Bhandup West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008977",
        label: "Kamothe",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006622",
        label: "Powai, Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002074",
        label: "Naupada",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008874",
        label: "Bhayandar West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001334",
        label: "Vileparle East",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008378",
        label: "Sion",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007690",
        label: "Nerul (Navi Mumbai)",
        cityName: "Mumbai",
    },
    {
        id: "ZWL007706",
        label: "Dahisar West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL005320",
        label: "Colaba",
        cityName: "Mumbai",
    },
    {
        id: "ZWL006544",
        label: "Mahim",
        cityName: "Mumbai",
    },
    {
        id: "ZWL002686",
        label: "Wadala",
        cityName: "Mumbai",
    },
    {
        id: "ZWL001089",
        label: "Borivali West",
        cityName: "Mumbai",
    },
    {
        id: "ZWL008360",
        label: "Palava Lakeshore,Mumbai",
        cityName: "Mumbai",
    },
    {
        id: "ZWL003467",
        label: "Banashankari",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL004900",
        label: "Rajarajeshwari Nagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL005530",
        label: "JP Nagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL007643",
        label: "Mahadevapura",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL003159",
        label: "Jalahalli",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL002736",
        label: "RT Nagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006369",
        label: "KR Puram",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006274",
        label: "Electronic City",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL005375",
        label: "Vijayanagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL008600",
        label: "Marathahalli",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL002292",
        label: "Sarjapur road",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL004341",
        label: "Brookefields",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL007633",
        label: "Whitefield",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL009212",
        label: "Nagavara",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL007628",
        label: "New BEL Road",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL001156",
        label: "Koramangala",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL004924",
        label: "Bannerghatta Road, Bangalore",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL009229",
        label: "Aavalahalli",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL005576",
        label: "BIAL Airport Road",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006658",
        label: "Yelahanka",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL002882",
        label: "Kadugodi",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006631",
        label: "Kammanahalli",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL001196",
        label: "HSR Layout",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006600",
        label: "BTM Layout",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006854",
        label: "Varthur",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL001273",
        label: "Indiranagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL008105",
        label: "Jayanagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL005206",
        label: "Sahakaranagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL008797",
        label: "Devanahalli, Bangalore",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL001962",
        label: "MG Road",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL006844",
        label: "Rajajinagar",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL004164",
        label: "Bellandur",
        cityName: "Bengaluru",
    },
    {
        id: "ZWL007698",
        label: "NIGDI(Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL005773",
        label: "Bibvewadi (Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL009577",
        label: "Nanded-Nahre",
        cityName: "Pune",
    },
    {
        id: "ZWL002253",
        label: "Bhosari (Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL003498",
        label: "Camp Area",
        cityName: "Pune",
    },
    {
        id: "ZWL004311",
        label: "Magarpatta",
        cityName: "Pune",
    },
    {
        id: "ZWL007801",
        label: "Pimpri",
        cityName: "Pune",
    },
    {
        id: "ZWL008134",
        label: "Yerwada",
        cityName: "Pune",
    },
    {
        id: "ZWL009625",
        label: "Kalyani Nagar (Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL001627",
        label: "Sus, Pune",
        cityName: "Pune",
    },
    {
        id: "ZWL006236",
        label: "Bavdhan",
        cityName: "Pune",
    },
    {
        id: "ZWL006743",
        label: "Viman nagar",
        cityName: "Pune",
    },
    {
        id: "ZWL004927",
        label: "Aundh (Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL008370",
        label: "Katraj (Pune)",
        cityName: "Pune",
    },
    {
        id: "ZWL004523",
        label: "Pimple Saudagar_Pune",
        cityName: "Pune",
    },
    {
        id: "ZWL001778",
        label: "Dhanori",
        cityName: "Pune",
    },
    {
        id: "ZWL003386",
        label: "Dehu Road",
        cityName: "Pune",
    },
    { id: "ZWL009157", label: "Koregaon Park (Pune)", cityName: "Pune" },
    { id: "ZWL004962", label: "Hinjewadi - Phase 2", cityName: "Pune" },
    { id: "ZWL005340", label: "Wakad_Pune", cityName: "Pune" },
    { id: "ZWL009671", label: "Manas Lake, Pune", cityName: "Pune" },
    { id: "ZWL008921", label: "Sadashiv Peth", cityName: "Pune" },
    { id: "ZWL008940", label: "Ghorpadi (Pune)", cityName: "Pune" },
    { id: "ZWL009874", label: "Pashan (Pune)", cityName: "Pune" },
    { id: "ZWL006660", label: "SP Infocity, Pune", cityName: "Pune" },
    { id: "ZWL003813", label: "Manjri,Pune", cityName: "Pune" },
    { id: "ZWL007471", label: "Khadki, Pune", cityName: "Pune" },
    { id: "ZWL009602", label: "Kothrud (Pune)", cityName: "Pune" },
    { id: "ZWL002208", label: "Sinhagad Road(Pune)", cityName: "Pune" },
    { id: "ZWL007895", label: "New Sangvi, Pune", cityName: "Pune" },
    { id: "ZWL003099", label: "Nimgaon, Pune", cityName: "Pune" },
    { id: "ZWL004575", label: "Wagholi", cityName: "Pune" },
    { id: "ZWL004513", label: "Keshavnagar, Pune", cityName: "Pune" },
    { id: "ZWL008983", label: "Baner (Pune)", cityName: "Pune" },
    { id: "ZWL005520", label: "Warje (Pune)", cityName: "Pune" },
    { id: "ZWL003300", label: "Mundwa, Pune", cityName: "Pune" },
    { id: "ZWL001963", label: "Chakan", cityName: "Pune" },
    { id: "ZWL002422", label: "Shivaji Nagar (Pune)", cityName: "Pune" },
    { id: "ZWL005088", label: "Yewalewadi, Pune", cityName: "Pune" },
    { id: "ZWL003014", label: "Bopkhel, Pune", cityName: "Pune" },
    { id: "ZWL001472", label: "Kharadi", cityName: "Pune" },
    { id: "ZWL004339", label: "Talegaon Dabhade", cityName: "Pune" },
    { id: "ZWL003817", label: "Hinjewadi - Phase 1", cityName: "Pune" },
    { id: "ZWL007925", label: "Wanowrie-Kondhwa", cityName: "Pune" },
    { id: "ZWL003370", label: "Nagole", cityName: "Hyderabad" },
    { id: "ZWL002088", label: "Attapur", cityName: "Hyderabad" },
    { id: "ZWL006702", label: "Peerzadiguda", cityName: "Hyderabad" },
    { id: "ZWL008776", label: "Begumpet", cityName: "Hyderabad" },
    { id: "ZWL003918", label: "Suraram, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL004079", label: "Banjara Hills", cityName: "Hyderabad" },
    { id: "ZWL008309", label: "Alwal", cityName: "Hyderabad" },
    { id: "ZWL002433", label: "Sainikpuri", cityName: "Hyderabad" },
    { id: "ZWL007390", label: "Saroor Nagar", cityName: "Hyderabad" },
    { id: "ZWL004767", label: "Karkhana", cityName: "Hyderabad" },
    { id: "ZWL006016", label: "Kompally", cityName: "Hyderabad" },
    { id: "ZWL003283", label: "Himayatnagar", cityName: "Hyderabad" },
    { id: "ZWL007311", label: "Medchal Road", cityName: "Hyderabad" },
    { id: "ZWL005919", label: "Kukatpally", cityName: "Hyderabad" },
    { id: "ZWL001822", label: "Amberpet", cityName: "Hyderabad" },
    { id: "ZWL008208", label: "Jeedimetla", cityName: "Hyderabad" },
    { id: "ZWL001362", label: "Gachibowli", cityName: "Hyderabad" },
    { id: "ZWL002162", label: "LB Nagar", cityName: "Hyderabad" },
    { id: "ZWL009712", label: "Dilsukhnagar", cityName: "Hyderabad" },
    { id: "ZWL005963", label: "Masab Tank", cityName: "Hyderabad" },
    { id: "ZWL008297", label: "Bachupally", cityName: "Hyderabad" },
    { id: "ZWL005424", label: "Manikonda", cityName: "Hyderabad" },
    { id: "ZWL008585", label: "Shamshabad", cityName: "Hyderabad" },
    { id: "ZWL008599", label: "Miyapur", cityName: "Hyderabad" },
    { id: "ZWL006535", label: "Hayath Nagar, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL006545", label: "Sangareddy, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL009719", label: "JNTU", cityName: "Hyderabad" },
    { id: "ZWL008890", label: "Serilingampally", cityName: "Hyderabad" },
    { id: "ZWL007119", label: "Nizampet", cityName: "Hyderabad" },
    { id: "ZWL004747", label: "Q City, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL004802", label: "Madhapur", cityName: "Hyderabad" },
    { id: "ZWL004665", label: "Narayanguda", cityName: "Hyderabad" },
    { id: "ZWL005999", label: "ECIL", cityName: "Hyderabad" },
    { id: "ZWL003360", label: "Toli Chowki", cityName: "Hyderabad" },
    { id: "ZWL007187", label: "Kondapur", cityName: "Hyderabad" },
    { id: "ZWL007344", label: "Charminar", cityName: "Hyderabad" },
    { id: "ZWL008438", label: "Sivarampalli", cityName: "Hyderabad" },
    { id: "ZWL005494", label: "Tarnaka", cityName: "Hyderabad" },
    { id: "ZWL009519", label: "Moosapet", cityName: "Hyderabad" },
    { id: "ZWL001687", label: "Patancheru, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL005569", label: "Vanasthali Puram", cityName: "Hyderabad" },
    { id: "ZWL003027", label: "Ameerpet", cityName: "Hyderabad" },
    { id: "ZWL001337", label: "Uppal", cityName: "Hyderabad" },
    { id: "ZWL001579", label: "Malakpet", cityName: "Hyderabad" },
    { id: "ZWL006699", label: "Hafiz Baba Nagar", cityName: "Hyderabad" },
    { id: "ZWL008512", label: "Mokila, Hyderabad", cityName: "Hyderabad" },
    { id: "ZWL006789", label: "Potheri", cityName: "Chennai" },
    { id: "ZWL004297", label: "Pallavaram", cityName: "Chennai" },
    { id: "ZWL005190", label: "Nungambakkam", cityName: "Chennai" },
    { id: "ZWL003967", label: "Anna Nagar, Chennai", cityName: "Chennai" },
    { id: "ZWL008996", label: "Perambur", cityName: "Chennai" },
    { id: "ZWL005857", label: "Mogappair, Chennai", cityName: "Chennai" },
    { id: "ZWL006232", label: "Royapuram", cityName: "Chennai" },
    { id: "ZWL008548", label: "Mugalivakkam", cityName: "Chennai" },
    { id: "ZWL006053", label: "Porur", cityName: "Chennai" },
    { id: "ZWL001398", label: "Redhills", cityName: "Chennai" },
    { id: "ZWL001701", label: "Tambaram", cityName: "Chennai" },
    { id: "ZWL008876", label: "Avadi", cityName: "Chennai" },
    { id: "ZWL003387", label: "Kilpauk", cityName: "Chennai" },
    { id: "ZWL007059", label: "Ashok Nagar (CHENNAI)", cityName: "Chennai" },
    { id: "ZWL006520", label: "Adyar", cityName: "Chennai" },
    { id: "ZWL001210", label: "Alwarpet", cityName: "Chennai" },
    { id: "ZWL007171", label: "Selaiyur", cityName: "Chennai" },
    { id: "ZWL006329", label: "Thandalam, Chennai", cityName: "Chennai" },
    { id: "ZWL004233", label: "Sholinganallur", cityName: "Chennai" },
    { id: "ZWL007209", label: "Ambattur", cityName: "Chennai" },
    { id: "ZWL003452", label: "Medavakkam", cityName: "Chennai" },
    { id: "ZWL007176", label: "Poonamallee", cityName: "Chennai" },
    { id: "ZWL009897", label: "Minjur, Chennai", cityName: "Chennai" },
    { id: "ZWL004882", label: "Urapakkam", cityName: "Chennai" },
    { id: "ZWL006156", label: "Velachery", cityName: "Chennai" },
    { id: "ZWL001141", label: "Navallur", cityName: "Chennai" },
    { id: "ZWL004431", label: "Vadapalani", cityName: "Chennai" },
    { id: "ZWL001516", label: "T Nagar", cityName: "Chennai" },
    { id: "ZWL003425", label: "Hazratganj", cityName: "Lucknow" },
    { id: "ZWL006490", label: "Aminabad", cityName: "Lucknow" },
    { id: "ZWL009091", label: "Chowk", cityName: "Lucknow" },
    { id: "ZWL003030", label: "Telibagh, Lucknow", cityName: "Lucknow" },
    { id: "ZWL004978", label: "Husainganj", cityName: "Lucknow" },
    { id: "ZWL009177", label: "Jankipuram", cityName: "Lucknow" },
    { id: "ZWL004436", label: "Arjunganj", cityName: "Lucknow" },
    { id: "ZWL005470", label: "Chinhat, Lucknow", cityName: "Lucknow" },
    { id: "ZWL001500", label: "Mahanagar", cityName: "Lucknow" },
    { id: "ZWL003371", label: "Ashiyana", cityName: "Lucknow" },
    { id: "ZWL003320", label: "Vasant Kunj, Lucknow", cityName: "Lucknow" },
    { id: "ZWL009682", label: "Rajajipuram", cityName: "Lucknow" },
    { id: "ZWL002273", label: "Gomti Nagar", cityName: "Lucknow" },
    { id: "ZWL002331", label: "Alambagh", cityName: "Lucknow" },
    { id: "ZWL007731", label: "Aliganj, Lucknow", cityName: "Lucknow" },
    { id: "ZWL007011", label: "Kalyanpur", cityName: "Lucknow" },
    { id: "ZWL003768", label: "Eroor", cityName: "Kochi" },
    { id: "ZWL005555", label: "Kakkanad", cityName: "Kochi" },
    { id: "ZWL002986", label: "Nedumbassery,Kochi", cityName: "Kochi" },
    { id: "ZWL004273", label: "North Paravur, Kochi", cityName: "Kochi" },
    { id: "ZWL005425", label: "Aluva, Kochi", cityName: "Kochi" },
    { id: "ZWL004691", label: "Ambalamugal", cityName: "Kochi" },
    { id: "ZWL001981", label: "Kalamassery", cityName: "Kochi" },
    { id: "ZWL003786", label: "Kaloor", cityName: "Kochi" },
    { id: "ZWL009487", label: "Perumbavoor,Kochi", cityName: "Kochi" },
    { id: "ZWL007216", label: "Thiruvankulam", cityName: "Kochi" },
    { id: "ZWL002327", label: "Vypin, Kochi", cityName: "Kochi" },
    { id: "ZWL006873", label: "Ernakulam", cityName: "Kochi" },
    { id: "ZWL004591", label: "Fort Kochi", cityName: "Kochi" },
    { id: "ZWL005082", label: "Mansarovar-2", cityName: "Jaipur" },
    { id: "ZWL003863", label: "Tonk road 2", cityName: "Jaipur" },
    { id: "ZWL009286", label: "Jagatpura", cityName: "Jaipur" },
    { id: "ZWL009458", label: "Shyam Nagar", cityName: "Jaipur" },
    { id: "ZWL003704", label: "C Scheme", cityName: "Jaipur" },
    { id: "ZWL003606", label: "Lal Kothi", cityName: "Jaipur" },
    { id: "ZWL009569", label: "Pink City", cityName: "Jaipur" },
    { id: "ZWL001750", label: "Vaishali Nagar", cityName: "Jaipur" },
    { id: "ZWL002751", label: "Malviya Nagar", cityName: "Jaipur" },
    { id: "ZWL005080", label: "Sodala", cityName: "Jaipur" },
    { id: "ZWL008680", label: "Vidhyadhar Nagar", cityName: "Jaipur" },
    { id: "ZWL008249", label: "Raja Park", cityName: "Jaipur" },
    { id: "ZWL008915", label: "Shastri Nagar", cityName: "Jaipur" },
    { id: "ZWL006372", label: "Pratap Nagar", cityName: "Jaipur" },
    { id: "ZWL003133", label: "Paldi", cityName: "Ahmedabad" },
    { id: "ZWL002302", label: "Shahibag", cityName: "Ahmedabad" },
    { id: "ZWL003747", label: "Navrangpura", cityName: "Ahmedabad" },
    { id: "ZWL002503", label: "Chandkheda", cityName: "Ahmedabad" },
    { id: "ZWL005979", label: "Science-City Sola", cityName: "Ahmedabad" },
    { id: "ZWL005987", label: "Sector 16, Gandhinagar", cityName: "Ahmedabad" },
    { id: "ZWL001959", label: "Vastrapur", cityName: "Ahmedabad" },
    { id: "ZWL007404", label: "Prahlad Nagar", cityName: "Ahmedabad" },
    { id: "ZWL001898", label: "Nikol", cityName: "Ahmedabad" },
    { id: "ZWL002250", label: "Infocity, Gandhinagar", cityName: "Ahmedabad" },
    { id: "ZWL004415", label: "Naranpura", cityName: "Ahmedabad" },
    { id: "ZWL006288", label: "Bopal", cityName: "Ahmedabad" },
    { id: "ZWL009182", label: "Maninagar", cityName: "Ahmedabad" },
    { id: "ZWL009990", label: "Bodakdev", cityName: "Ahmedabad" },
    { id: "ZWL003455", label: "Gota", cityName: "Ahmedabad" },
    { id: "ZWL007561", label: "Sector 15 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL006687", label: "Sector 8 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL001934", label: "Manimajra (Chandigarh)", cityName: "Chandigarh" },
    {
        id: "ZWL003936",
        label: "Industrial Area Phase I (Chandigarh)",
        cityName: "Chandigarh",
    },
    { id: "ZWL004716", label: "Sector 59 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL002303", label: "Sector 20, Panchkula", cityName: "Chandigarh" },
    { id: "ZWL009521", label: "Sector 8/9 nd Panchkula", cityName: "Chandigarh" },
    { id: "ZWL006817", label: "Sector 28 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL003496", label: "Phase 10 Mohali", cityName: "Chandigarh" },
    { id: "ZWL009894", label: "Gillco, Chandigarh", cityName: "Chandigarh" },
    { id: "ZWL004101", label: "Sector 46 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL003262", label: "Sector 70 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL009430", label: "VIP Road, Zirakpur", cityName: "Chandigarh" },
    { id: "ZWL004196", label: "VR Mall", cityName: "Chandigarh" },
    { id: "ZWL003093", label: "Sector 35 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL009406", label: "Sector 22 (Chandigarh)", cityName: "Chandigarh" },
    { id: "ZWL002150", label: "Verna, Goa", cityName: "Goa" },
    { id: "ZWL008519", label: "Mapusa, Goa", cityName: "Goa" },
    { id: "ZWL004452", label: "Calangute, Goa", cityName: "Goa" },
    { id: "ZWL006556", label: "Majorda, Goa", cityName: "Goa" },
    { id: "ZWL002137", label: "Upper panaji, Goa", cityName: "Goa" },
    { id: "ZWL005093", label: "Ponda, Goa", cityName: "Goa" },
    { id: "ZWL002142", label: "Margao, Goa", cityName: "Goa" },
    { id: "ZWL004621", label: "Vasco, Goa", cityName: "Goa" },
    { id: "ZWL006403", label: "Morjim, Goa", cityName: "Goa" },
    { id: "ZWL005568", label: "Porvorim, Goa", cityName: "Goa" },
    { id: "ZWL009021", label: "Sector 32, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL006208", label: "Civil Lines, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL006788", label: "Sarabha Nagar, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL005256", label: "BRS Nagar, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL001163", label: "Model Town, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL003304", label: "Ganesh Nagar, Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL003119", label: "Dugri,Ludhiana", cityName: "Ludhiana" },
    { id: "ZWL006981", label: "Pathar Quarry, Guwahati", cityName: "Guwahati" },
    { id: "ZWL006537", label: "Basistha-Lokhra, Guwahati", cityName: "Guwahati" },
    { id: "ZWL009407", label: "North Guwahati, Guwahati", cityName: "Guwahati" },
    { id: "ZWL004763", label: "Dharapur, Guwahati", cityName: "Guwahati" },
    {
        id: "ZWL007095",
        label: "Lal Ganesh - Kahilipara, Guwahati",
        cityName: "Guwahati",
    },
    { id: "ZWL002105", label: "Paltan-Bazar, Guwahati", cityName: "Guwahati" },
    { id: "ZWL003362", label: "Azara, Guwahati", cityName: "Guwahati" },
    { id: "ZWL002491", label: "Changsari, Guwahati", cityName: "Guwahati" },
    {
        id: "ZWL005319",
        label: "Maligaon - Jalukbari, Guwahati",
        cityName: "Guwahati",
    },
    {
        id: "ZWL005708",
        label: "Zoo Tiniali - Christian basti",
        cityName: "Guwahati",
    },
    { id: "ZWL001780", label: "Himatpura, Amritsar", cityName: "Amritsar" },
    { id: "ZWL008281", label: "Rasulpur, Amritsar", cityName: "Amritsar" },
    { id: "ZWL004590", label: "Ranjit Avenue, Amritsar", cityName: "Amritsar" },
    { id: "ZWL002073", label: "White Avenue, Amritsar", cityName: "Amritsar" },
    { id: "ZWL005826", label: "Chheharta, Amritsar", cityName: "Amritsar" },
    { id: "ZWL007456", label: "Hall Bazar, Amritsar", cityName: "Amritsar" },
    { id: "ZWL008755", label: "Ashoka Garden, Bhopal", cityName: "Bhopal" },
    { id: "ZWL009428", label: "Shahpura,Bhopal", cityName: "Bhopal" },
    { id: "ZWL006900", label: "Airport Area, Bhopal", cityName: "Bhopal" },
    { id: "ZWL002615", label: "TT Nagar, Bhopal", cityName: "Bhopal" },
    { id: "ZWL003463", label: "BHEL, Bhopal", cityName: "Bhopal" },
    { id: "ZWL002872", label: "MP Nagar,Bhopal", cityName: "Bhopal" },
    { id: "ZWL005836", label: "Hoshangabad Road, Bhopal", cityName: "Bhopal" },
    { id: "ZWL003417", label: "People's Mall, Bhopal", cityName: "Bhopal" },
    { id: "ZWL001466", label: "NAD, Vizag", cityName: "Visakhapatnam" },
    { id: "ZWL003024", label: "Gajuwaka", cityName: "Visakhapatnam" },
    { id: "ZWL004755", label: "Dwaraka Nagar", cityName: "Visakhapatnam" },
    { id: "ZWL009959", label: "Madhurawada", cityName: "Visakhapatnam" },
    {
        id: "ZWL007491",
        label: "Madhusudan Nagar, Bhubaneswar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL003084",
        label: "Kalinga Nagar, Bhubneshwar",
        cityName: "Bhubaneswar",
    },
    { id: "ZWL003270", label: "Nayapalli, Bhubneshwar", cityName: "Bhubaneswar" },
    {
        id: "ZWL007379",
        label: "Sahid Nagar, Bhubaneshwar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL001823",
        label: "Lakshmi Sagar, Bhubneshwar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL004098",
        label: "Khandagiri, Bhubaneswar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL008906",
        label: "Jagmohan Nagar, Bhubaneswar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL002821",
        label: "Kharabela Nagar, Bhubaneswar",
        cityName: "Bhubaneswar",
    },
    {
        id: "ZWL009572",
        label: "Chandrasekharpur, Bhubaneswar",
        cityName: "Bhubaneswar",
    },
    { id: "ZWL005652", label: "Patia, Bhubneshwar", cityName: "Bhubaneswar" },
    { id: "ZWL003661", label: "Gandhipuram, Coimbatore", cityName: "Coimbatore" },
    { id: "ZWL005742", label: "Vadavalli", cityName: "Coimbatore" },
    { id: "ZWL008653", label: "RS Puram, Coimbatore", cityName: "Coimbatore" },
    { id: "ZWL002703", label: "Racecourse, Coimbatore", cityName: "Coimbatore" },
    {
        id: "ZWL009668",
        label: "Saibaba Colony, Coimbatore",
        cityName: "Coimbatore",
    },
    { id: "ZWL007527", label: "Peelamedu, Coimbatore", cityName: "Coimbatore" },
    { id: "ZWL005468", label: "Podanur, Coimbatore", cityName: "Coimbatore" },
    {
        id: "ZWL004408",
        label: "Kunniamuthur, Coimbatore",
        cityName: "Coimbatore",
    },
    { id: "ZWL008265", label: "Ondipudur, Coimbatore", cityName: "Coimbatore" },
    { id: "ZWL007600", label: "Koundampalayam", cityName: "Coimbatore" },
    { id: "ZWL002147", label: "Saravanampatty", cityName: "Coimbatore" },
    {
        id: "ZWL009595",
        label: "Ganapathypudur, Coimbatore",
        cityName: "Coimbatore",
    },
    {
        id: "ZWL001279",
        label: "Sitra, and Singanallur, Coimbatore",
        cityName: "Coimbatore",
    },
    { id: "ZWL006449", label: "South Mangalore", cityName: "Mangalore" },
    { id: "ZWL009478", label: "Thokkattu, Mangalore", cityName: "Mangalore" },
    { id: "ZWL002354", label: "Waghodia", cityName: "Vadodara" },
    { id: "ZWL004097", label: "Fatehgunj", cityName: "Vadodara" },
    { id: "ZWL009713", label: "Nizampura", cityName: "Vadodara" },
    { id: "ZWL008938", label: "Diwalipura", cityName: "Vadodara" },
    { id: "ZWL004439", label: "Akota", cityName: "Vadodara" },
    { id: "ZWL002446", label: "Manjalpur, Vadodara", cityName: "Vadodara" },
    { id: "ZWL008232", label: "Shubhanpura", cityName: "Vadodara" },
    { id: "ZWL002475", label: "Alkapuri", cityName: "Vadodara" },
    { id: "ZWL005549", label: "Pratap Nagar", cityName: "Nagpur" },
    { id: "ZWL001438", label: "Sadar", cityName: "Nagpur" },
    { id: "ZWL006432", label: "Kharabi, Nagpur", cityName: "Nagpur" },
    { id: "ZWL009782", label: "Hanuman Nagar", cityName: "Nagpur" },
    { id: "ZWL008282", label: "Dharampeth", cityName: "Nagpur" },
    { id: "ZWL001041", label: "Manish Nagar", cityName: "Nagpur" },
    { id: "ZWL007188", label: "Ayodhya Nagar, Nagpur", cityName: "Nagpur" },
    { id: "ZWL003633", label: "Gandhibagh", cityName: "Nagpur" },
    { id: "ZWL002458", label: "Central Mysore", cityName: "Mysore" },
    { id: "ZWL005095", label: "Udhna, Surat", cityName: "Surat" },
    { id: "ZWL002155", label: "City Light, Surat", cityName: "Surat" },
    { id: "ZWL007951", label: "Athwa", cityName: "Surat" },
    { id: "ZWL006000", label: "Vesu, Surat", cityName: "Surat" },
    { id: "ZWL008198", label: "Adajan, Surat", cityName: "Surat" },
    { id: "ZWL002771", label: "Varaccha, Surat", cityName: "Surat" },
    { id: "ZWL005626", label: "New Textile Market, Surat", cityName: "Surat" },
    { id: "ZWL005423", label: "Katargam, Surat", cityName: "Surat" },
    {
        id: "ZWL009343",
        label: "Kazhakoottam, Thiruvananthapuram",
        cityName: "Trivandrum",
    },
    { id: "ZWL007746", label: "Tvm Central", cityName: "Trivandrum" },
    {
        id: "ZWL002223",
        label: "Nemom, Thiruvananthapuram",
        cityName: "Trivandrum",
    },
    { id: "ZWL005308", label: "Governorpet, Vijayawada", cityName: "Vijayawada" },
    { id: "ZWL004428", label: "Gunadala, Vijayawada", cityName: "Vijayawada" },
    { id: "ZWL002106", label: "Gollapudi, Vijayawada", cityName: "Vijayawada" },
    { id: "ZWL005858", label: "Auto Nagar, Vijayawada", cityName: "Vijayawada" },
    { id: "ZWL003905", label: "Labbipet, Vijayawada", cityName: "Vijayawada" },
    { id: "ZWL009921", label: "Shastri Nagar, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL002344", label: "Gurdev Nagar, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL001077", label: "Paragpur, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL005408", label: "Model Town, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL001624", label: "Basti Nau, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL004713", label: "Rama Mandi, Jalandhar", cityName: "Jalandhar" },
    { id: "ZWL007457", label: "Greater Kailash, Jammu", cityName: "Jammu" },
    { id: "ZWL005892", label: "Barnai, Jammu", cityName: "Jammu" },
    { id: "ZWL008753", label: "Gandhi Nagar, Jammu", cityName: "Jammu" },
    { id: "ZWL008047", label: "OLD JAMMU, Jammu", cityName: "Jammu" },
    { id: "ZWL002687", label: "Channi Himmat, Jammu", cityName: "Jammu" },
    { id: "ZWL003195", label: "Shankar Nagar, Raipur", cityName: "Raipur" },
    { id: "ZWL009896", label: "Purena, Raipur", cityName: "Raipur" },
    { id: "ZWL001038", label: "Mowa, Raipur", cityName: "Raipur" },
    { id: "ZWL008872", label: "Mahaveer Nagar", cityName: "Raipur" },
    { id: "ZWL004310", label: "Samta Colony, Raipur", cityName: "Raipur" },
    { id: "ZWL006651", label: "Civil Lines, Raipur", cityName: "Raipur" },
    { id: "ZWL008695", label: "Devendra Nagar, Raipur", cityName: "Raipur" },
    { id: "ZWL008436", label: "Moudhapara, Raipur", cityName: "Raipur" },
];
